<a href="https://colab.research.google.com/github/klinhha/E-Wallet-Company-Data-Wrangling-Exploratory-Analysis/blob/main/Khanh_Linh_Ha_Data_Wrangling_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Given dataset**

Suppose you are a DA in an e-wallet company, and you need to analyze the following datasets:
- payment_report.csv (monthly payment volume of products)
- product.csv (product information)
- transactions.csv (transactions information)

In [ ]:
# Import necessary libraries
import numpy as np
import pandas as pd
import os
import warnings
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [ ]:
# Mount Google Drive to Colab
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Import CSV files into Colab
transactions = pd.read_csv('/content/drive/MyDrive/Python - Data_Wrangling_project/transactions.csv')
product = pd.read_csv('/content/drive/MyDrive/Python - Data_Wrangling_project/product.csv')
payment = pd.read_csv('/content/drive/MyDrive/Python - Data_Wrangling_project/payment_report.csv')

In [ ]:
product

     product_id category team_own
0            17  PXXXXXB      ASD
1            18  PXXXXXB      ASD
2            20  PXXXXXB      ASD
3           287  PXXXXXB      ASD
4           372  PXXXXXB      ASD
..          ...      ...      ...
487         321  PXXXXXV      ASD
488         322  PXXXXXV      ASD
489         341  PXXXXXV      ASD
490         342  PXXXXXV      ASD
491         367  PXXXXXV      ASD

[492 rows x 3 columns]

In [ ]:
transactions

,transaction_id,merchant_id,volume,transType,transStatus,sender_id,receiver_id,extra_info,timeStamp
0,3002692434,5,100000,24,1,10199794.0,199794.0,NaN,1682932054455
1,3002692437,305,20000,2,1,14022211.0,14022211.0,NaN,1682932054912
2,3001960110,7255,48605,22,1,NaN,10530940.0,NaN,1682932055000
3,3002680710,2270,1500000,2,1,10059206.0,59206.0,NaN,1682932055622
4,3002680713,2275,90000,2,1,10004711.0,4711.0,NaN,1682932056197
...,...,...,...,...,...,...,...,...,...
1323997,3003723030,305,20000,2,1,24524311.0,NaN,NaN,1683035672634
1323998,3003723033,2270,100000,2,1,10277242.0,277242.0,NaN,1683035672876
1323999,3003723036,2270,100000,2,1,10144599.0,144599.0,NaN,1683035672892
1324000,3003723039,5,400,22,1,10028007.0,21013762.0,NaN,1683035672896
1324001,3003602967,2250,1,8,1,38559843.0,24501638.0,NaN,1683035673053

In [ ]:
payment

    report_month payment_group  product_id  source_id       volume
0        2023-01       payment          12         45    624110375
1        2023-01       payment          17         45    335715113
2        2023-01       payment          18         45    737784466
3        2023-01       payment          19         45    120963069
4        2023-01       payment          20         45    319653158
..           ...           ...         ...        ...          ...
914      2023-04       payment       15067         45      1504000
915      2023-04        refund        1976         37   3542271587
916      2023-04        refund        1976         38  13831708189
917      2023-04        refund        1976         39   1905435543
918      2023-04        refund        1976         39   3679922071

[919 rows x 5 columns]

### **PART I: Explore Data Analysis (EDA)**

In [ ]:
# Merge payment with product
payment_enriched = payment.merge(product, on = 'product_id', how = 'left')

In [ ]:
payment_enriched

,report_month,payment_group,product_id,source_id,volume,category,team_own
0,2023-01,payment,12,45,624110375,PXXXXXT,ASD
1,2023-01,payment,17,45,335715113,PXXXXXB,ASD
2,2023-01,payment,18,45,737784466,PXXXXXB,ASD
3,2023-01,payment,19,45,120963069,PXXXXXM2,ASD
4,2023-01,payment,20,45,319653158,PXXXXXB,ASD
...,...,...,...,...,...,...,...
914,2023-04,payment,15067,45,1504000,PXXXXXR,ASL
915,2023-04,refund,1976,37,3542271587,NaN,NaN
916,2023-04,refund,1976,38,13831708189,NaN,NaN
917,2023-04,refund,1976,39,1905435543,NaN,NaN
918,2023-04,refund,1976,39,3679922071,NaN,NaN

In [ ]:
# Check Data type

In [ ]:
payment_enriched.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 919 entries, 0 to 918
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   report_month   919 non-null    object
 1   payment_group  919 non-null    object
 2   product_id     919 non-null    int64
 3   source_id      919 non-null    int64
 4   volume         919 non-null    int64
 5   category       897 non-null    object
 6   team_own       897 non-null    object
dtypes: int64(3), object(4)
memory usage: 50.4+ KB

=> **Incorrect Data type** in column "report_month"

In [ ]:
# Convert the report_month column from object to datetime
payment_enriched['report_month'] = pd.to_datetime(payment_enriched['report_month'])

In [ ]:
payment_enriched.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 919 entries, 0 to 918
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   report_month   919 non-null    datetime64[ns]
 1   payment_group  919 non-null    object
 2   product_id     919 non-null    int64
 3   source_id      919 non-null    int64
 4   volume         919 non-null    int64
 5   category       897 non-null    object
 6   team_own       897 non-null    object
dtypes: datetime64[ns](1), int64(3), object(3)
memory usage: 50.4+ KB

In [ ]:
product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 492 entries, 0 to 491
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product_id  492 non-null    int64
 1   category    492 non-null    object
 2   team_own    492 non-null    object
dtypes: int64(1), object(2)
memory usage: 11.7+ KB

=> No Incorrect data type

In [ ]:
payment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 919 entries, 0 to 918
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   report_month   919 non-null    object
 1   payment_group  919 non-null    object
 2   product_id     919 non-null    int64
 3   source_id      919 non-null    int64
 4   volume         919 non-null    int64
dtypes: int64(3), object(2)
memory usage: 36.0+ KB

=> **Incorrect Data type** in column "report_month"

In [ ]:
# Convert the report_month column from object to datetime
payment['report_month'] = pd.to_datetime(payment['report_month'])

In [ ]:
payment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 919 entries, 0 to 918
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   report_month   919 non-null    datetime64[ns]
 1   payment_group  919 non-null    object
 2   product_id     919 non-null    int64
 3   source_id      919 non-null    int64
 4   volume         919 non-null    int64
dtypes: datetime64[ns](1), int64(3), object(1)
memory usage: 36.0+ KB

In [ ]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1324002 entries, 0 to 1324001
Data columns (total 9 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   transaction_id  1324002 non-null  int64
 1   merchant_id     1324002 non-null  int64
 2   volume          1324002 non-null  int64
 3   transType       1324002 non-null  int64
 4   transStatus     1324002 non-null  int64
 5   sender_id       1274943 non-null  float64
 6   receiver_id     1159207 non-null  float64
 7   extra_info      6095 non-null     object
 8   timeStamp       1324002 non-null  int64
dtypes: float64(2), int64(6), object(1)
memory usage: 90.9+ MB

=> **Incorrect Data type** in column "timeStamp"

In [ ]:
# Convert 'timeStamp' from int64 to datetime
transactions['timeStamp'] = pd.to_datetime(transactions['timeStamp'])

In [ ]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1324002 entries, 0 to 1324001
Data columns (total 9 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   transaction_id  1324002 non-null  int64
 1   merchant_id     1324002 non-null  int64
 2   volume          1324002 non-null  int64
 3   transType       1324002 non-null  int64
 4   transStatus     1324002 non-null  int64
 5   sender_id       1274943 non-null  float64
 6   receiver_id     1159207 non-null  float64
 7   extra_info      6095 non-null     object
 8   timeStamp       1324002 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(5), object(1)
memory usage: 90.9+ MB

In [ ]:
# Check for missing values

In [ ]:
payment.isnull().sum()

report_month     0
payment_group    0
product_id       0
source_id        0
volume           0
dtype: int64

**=> No missing value**

In [ ]:
product.isnull().sum()

product_id    0
category      0
team_own      0
dtype: int64

**=> No missing value**

In [ ]:
transactions.isnull().sum()

transaction_id          0
merchant_id             0
volume                  0
transType               0
transStatus             0
sender_id           49059
receiver_id        164795
extra_info        1317907
timeStamp               0
dtype: int64

**=> Missing values:**  

*   *49059 rows* in column 'sender_id'
*   *164795 rows* in column 'receiver_id'
*   *1317907 rows* in column 'extra_info'

In [ ]:
# The sender_id and receiver_id columns in the Transaction table are not important, so missing values are replaced with 'Unknow' for consistency
transactions['sender_id'] = transactions['sender_id'].fillna(value='Unknow')
transactions['receiver_id'] = transactions['receiver_id'].fillna(value='Unknow')

# Drop the 'extra_info' column from the Transaction table
transactions.drop('extra_info', axis=1, inplace=True)

In [ ]:
# Check for duplicates
duplicate_payment = payment.duplicated().sum()
duplicate_product = product.duplicated().sum()
duplicate_transactions = transactions.duplicated().sum()

# Print results
print("Number of duplicates in payment: ", duplicate_payment)
print("Number of duplicates in product: ", duplicate_product)
print("Number of duplicates in transaction: ", duplicate_transactions)

Number of duplicates in payment:  0
Number of duplicates in product:  0
Number of duplicates in transaction:  28

In [ ]:
#Drop duplicate
transactions.drop_duplicates(subset=None, keep='first')

,transaction_id,merchant_id,volume,transType,transStatus,sender_id,receiver_id,timeStamp
0,3002692434,5,100000,24,1,10199794.0,199794.0,1970-01-01 00:28:02.932054455
1,3002692437,305,20000,2,1,14022211.0,14022211.0,1970-01-01 00:28:02.932054912
2,3001960110,7255,48605,22,1,Unknow,10530940.0,1970-01-01 00:28:02.932055000
3,3002680710,2270,1500000,2,1,10059206.0,59206.0,1970-01-01 00:28:02.932055622
4,3002680713,2275,90000,2,1,10004711.0,4711.0,1970-01-01 00:28:02.932056197
...,...,...,...,...,...,...,...,...
1323997,3003723030,305,20000,2,1,24524311.0,Unknow,1970-01-01 00:28:03.035672634
1323998,3003723033,2270,100000,2,1,10277242.0,277242.0,1970-01-01 00:28:03.035672876
1323999,3003723036,2270,100000,2,1,10144599.0,144599.0,1970-01-01 00:28:03.035672892
1324000,3003723039,5,400,22,1,10028007.0,21013762.0,1970-01-01 00:28:03.035672896
1324001,3003602967,2250,1,8,1,38559843.0,24501638.0,1970-01-01 00:28:03.035673053

In [ ]:
# Numerical data: No incorrect values
payment_enriched.describe()

                        report_month    product_id   source_id        volume
count                            919    919.000000  919.000000  9.190000e+02
mean   2023-02-19 06:05:05.549510400   1192.517954   44.875952  1.978574e+08
min              2023-01-01 00:00:00      3.000000   37.000000  5.500000e+03
25%              2023-02-01 00:00:00    640.000000   45.000000  1.250000e+06
50%              2023-03-01 00:00:00   1059.000000   45.000000  7.982015e+06
75%              2023-04-01 00:00:00   1585.000000   45.000000  5.447599e+07
max              2023-04-01 00:00:00  15067.000000   45.000000  1.383171e+10
std                              NaN   1293.463329    0.910995  8.367595e+08

### **PART II: Data Wrangling**

### Using payment_report.csv & product.csv

**Q1.** Top 3 product_ids with the highest volume

In [ ]:
payment_enriched.groupby("product_id",
                         as_index = False).agg({'volume':'sum'}).sort_values('volume',
                                                                              ascending = False).head(3)

     product_id       volume
279        1976  61797583647
43          429  14667676567
38          372  13713658515

**Q2.** Given that 1 product_id is only owed by 1 team, are there any abnormal products against this rule?

In [ ]:
# Group by product_id and count the number of unique team_own values
abnormal = payment_enriched.groupby("product_id",
                         as_index = False).agg({'team_own': 'nunique'}) #nunique is similar to DISTINCT COUNT

# Identify product_id entries managed by more than one team
abnormal_products = abnormal[abnormal["team_own"]>1]

# Print the results
if abnormal_products.empty:
  print('No abnormal products against this rule')
else:
  print('There are abnormal products against this rule:')
  print(abnormal_products)

No abnormal products against this rule

**Q3.** Find the team has had the lowest performance (lowest volume) since Q2.2023. Find the category that contributes the least to that team.

**a.** Find the team has had the lowest performance (lowest volume) since Q2.2023.

In [ ]:
# Filter data from Q2.2023 onwards
Q2_2023 = payment_enriched[payment_enriched['report_month'] >= '2023-04-01']

# Find the team with the lowest total volume
lowest_volume = (
    Q2_2023.groupby('team_own', as_index=False)
    .agg({'volume': 'sum'})
    .sort_values('volume')
    .head(1)
)
lowest_volume

  team_own    volume
0      APS  51141753

=> The lowest performance team in Q2.2023 is **APS** with **volume = 51141753**

**b.** Find the category that contributes the least to that team.

In [ ]:
# Filter data for the lowest-performing team since Q2.2023
team_APS = Q2_2023[Q2_2023['team_own'] == 'APS']

# Find the category with the lowest total volume
least_contribution = (team_APS.groupby('category', as_index=False)
    .agg({'volume': 'sum'})
    .sort_values('volume')
    .head(1)
)

least_contribution

  category    volume
0  PXXXXXE  25232438

=> The lowest contributing category to the team APS is **PXXXXXE** with **volume = 25232438**

**Q4.** Find the contribution of source_ids of refund transactions (payment_group = ‘refund’), what is the source_id with the highest contribut

In [ ]:
# Filter transactions that are refunds
refund = payment_enriched[payment_enriched['payment_group'] == 'refund']

# Calculate total volume by each source_id
refund_volume = refund.groupby("source_id",
                         as_index = False).agg({'volume': 'sum'}).sort_values('volume',
                                                                              ascending = False)

# Calculate the percentage contribution of each source_id
refund_volume['contribution'] = (refund_volume["volume"]/ refund_volume["volume"].sum() * 100)

print(refund_volume)

# Get the source_id with the highest contribution
top_source = refund_volume.loc[
    refund_volume['volume'] == refund_volume['volume'].max()].iloc[0]

source_id = top_source['source_id']
contribute = top_source['contribution']

print(
    f"{source_id} is the highest contributor to refund transactions "
    f"with {contribute:.2f}% contribution."
)

   source_id       volume  contribution
1         38  36527454759     59.108225
2         39  16119059662     26.083641
0         37   9151069226     14.808134
38.0 is the highest contributor to refund transactions with 59.11% contribution.

 **Q5.** Define type of transactions (‘transaction_type’) for each row, given:
- transType = 2 & merchant_id = 1205: Bank Transfer Transaction
- transType = 2 & merchant_id = 2260: Withdraw Money Transaction
- transType = 2 & merchant_id = 2270: Top Up Money Transaction
- transType = 2 & others merchant_id: Payment Transaction
- transType = 8, merchant_id = 2250: Transfer Money Transaction
- transType = 8 & others merchant_id: Split Bill Transaction
- Remained cases are invalid transactions

In [ ]:
# Define conditions for transaction types
def clasify_transaction(row):
  if row["transType"] == 2 and row["merchant_id"] == 1205:
    return "Bank Transfer Transaction"

  elif row["transType"] == 2 and row["merchant_id"] == 2260:
    return "Withdraw Money Transaction"

  elif row["transType"] == 2 and row["merchant_id"] == 2270:
    return "Top Up Money Transaction"

  elif row["transType"] == 2:
    return "Payment Transaction"

  elif row["transType"] == 8 and row["merchant_id"] == 2250:
    return "Transfer Money Transaction"

  elif row["transType"] == 8:
    return "Split Bill Transaction"

  else:
    return "Invalid Transactions"

# Assign transaction types based on conditions
transactions["transaction_type"] = transactions.apply(clasify_transaction, axis = 1)

transactions

,transaction_id,merchant_id,volume,transType,transStatus,sender_id,receiver_id,timeStamp,transaction_type
0,3002692434,5,100000,24,1,10199794.0,199794.0,1970-01-01 00:28:02.932054455,Invalid Transactions
1,3002692437,305,20000,2,1,14022211.0,14022211.0,1970-01-01 00:28:02.932054912,Payment Transaction
2,3001960110,7255,48605,22,1,Unknow,10530940.0,1970-01-01 00:28:02.932055000,Invalid Transactions
3,3002680710,2270,1500000,2,1,10059206.0,59206.0,1970-01-01 00:28:02.932055622,Top Up Money Transaction
4,3002680713,2275,90000,2,1,10004711.0,4711.0,1970-01-01 00:28:02.932056197,Payment Transaction
...,...,...,...,...,...,...,...,...,...
1323997,3003723030,305,20000,2,1,24524311.0,Unknow,1970-01-01 00:28:03.035672634,Payment Transaction
1323998,3003723033,2270,100000,2,1,10277242.0,277242.0,1970-01-01 00:28:03.035672876,Top Up Money Transaction
1323999,3003723036,2270,100000,2,1,10144599.0,144599.0,1970-01-01 00:28:03.035672892,Top Up Money Transaction
1324000,3003723039,5,400,22,1,10028007.0,21013762.0,1970-01-01 00:28:03.035672896,Invalid Transactions
1324001,3003602967,2250,1,8,1,38559843.0,24501638.0,1970-01-01 00:28:03.035673053,Transfer Money Transaction

**Q6.** Of each transaction type (excluding invalid transactions): find the number of transactions, volume, senders and receivers.

In [ ]:
#excluding invalid transactions
transactions_valid = transactions[transactions["transaction_type"] != "Invalid Transactions"]

# Group by transaction type and calculate the required metrics
transaction_number = transactions_valid.groupby("transaction_type",
                                                as_index = False).agg({"transaction_id": "count",
                                                                       "volume" : "sum",
                                                                       "sender_id" : "nunique",
                                                                       "receiver_id" : "nunique"})

transaction_number

,transaction_type,transaction_id,volume,sender_id,receiver_id
0,Bank Transfer Transaction,37879,50605806190,23156,9272
1,Payment Transaction,398677,71851515181,139583,113299
2,Split Bill Transaction,1376,4901464,1323,572
3,Top Up Money Transaction,290502,108606478829,110409,110409
4,Transfer Money Transaction,341177,37033171492,39021,34585
5,Withdraw Money Transaction,33725,23418181420,24814,24814